FROM ubuntu:latest
MAINTAINER pallav malviya "mpallav@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential libmysqlclient-dev
RUN apt-get install -y mysql-client
RUN apt-get install -y iputils-ping

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
